//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anidar.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Persona
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Ingresá el nombre.")]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "Ingresá la edad.")]
        public string Edad { get; set; }

        [Required(ErrorMessage = "Ingresá las semanas de embarazo.")]
        [DisplayName("Semanas de embarazo")]
        public string SemanasEmabarazo { get; set; }

        public string Domicilio { get; set; }

        public string Telefono { get; set; }

        public string Instagram { get; set; }

    }
}
